### ISSUE TITLE
Entry Validator lowercase remove

### ISSUE THREAD

**Issue by wakonig** [bec-project/bec_widgets#568]
Migrated from GitLab issue https://gitlab.psi.ch/bec/bec_widgets/-/issues/564

**Comment by wyzula-jan** [comment]
Cannot reproduce, I added two devices with Uppercase and plots works fine:

```yaml

Eiger:
  readoutPriority: async
  deviceClass: ophyd_devices.SimCamera
  deviceConfig:
    device_access: true
  deviceTags:
    - detector
  enabled: true
  readOnly: false
  softwareTrigger: true

Samx:
  readoutPriority: baseline
  deviceClass: ophyd_devices.SimPositioner
  deviceConfig:
    delay: 1
    limits:
      - -50
      - 50
    tolerance: 0.01
    update_frequency: 400
  deviceTags:
    - user motors
  enabled: true
  readOnly: false
```

<img width="912" alt="Image" src="https://github.com/user-attachments/assets/efa8b26b-9c34-490f-81c9-2643235fd7d0" />
